### PR TITLE
readme update

### PR DESCRIPTION
**Pull request by clanderson87**
Updates the readme. Already mucked up master with the initial files. in app.js I think I deleted a return?

### CODE REVIEW

**Comment by jcockhren** [comment]
@clanderson87 Take a look at the rendered version, the formatting is not appearing. You can practice your markdown in the PR comment box to see if it works the way you think.

https://github.com/jcockhren/e2-serve-a-survey/blob/513cdc690ea69fdc81c28952567ef6cfe63f36c5/README.md

**Comment by AdamSheaffer** [comment]
@clanderson87 
Depending on your editor, you should be able to find some packages that will preview markdown for you. I know most of you guys use sublime. I'm sure there's something out there for that.

Did you want app.js included in this PR? It also looks like this file is in the root of the project? When you do go to check that in make sure that it comes with a package.json file that lists angular and all of it's dependancies that you're using

**Comment by clanderson87** [comment]
@jcockhren Updated the styling. Thanks for the tip.
@AdamSheaffer I deleted the app.js from this PR. Didn't realize it wasn't in the correct directory, and I didn't really do anything to it this time.

**Comment by clanderson87** [comment]
@leifehetland @jonathanhuffaker Give a thumbs up or something in this convo. Or say you hate it. Whatevs.

**Comment by jcockhren** [comment]
@clanderson87 nice. :+1:

**Comment by jonathanhuffaker** [comment]
thumbs up on my end

**Comment by AdamSheaffer** [comment]
Nice :+1:

**Pull request merged**
